AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'brandline-site-settings-api.

  '
Globals:
  Function:
    Timeout: 300
Parameters:
  EnvStageName:
    Default: dev
    Description: The Environment name (e.g. dev, prod, etc.)
    Type: String
  Region:
    Default: us-west-2
    Description: The region to deploy the managed services
    Type: String
Mappings:
  cognito:
    dev:
      auth: arn:aws:cognito-idp:us-west-2:227466753703:userpool/us-west-2_4CNnR0d4H
Resources:
  SiteSettingsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: EnvStageName
      OpenApiVersion: 3.0.1
      Auth:
        Authorizers:
          BLCognitoAuth:
            UserPoolArn:
              Fn::FindInMap:
              - cognito
              - Ref: EnvStageName
              - auth
  SiteSettingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://brandline/e624910cfc7eec910bf15cbfbe19473c
      Handler: app.lambda_handler
      FunctionName:
        Fn::Sub: ${AWS::StackName}-SiteSettings-${EnvStageName}
      Events:
        GetSiteSettingsInfoEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: SiteSettingsAPI
            Path: /site-settings
            Method: get
            Auth:
              Authorizer: BLCognitoAuth
        PatchSiteSettingsInfoEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: SiteSettingsAPI
            Path: /site-settings
            Method: patch
            Auth:
              Authorizer: BLCognitoAuth
      Runtime: python3.7
      MemorySize: 128
      Environment:
        Variables:
          REGION:
            Ref: Region
          LAMBDA_ENV:
            Ref: EnvStageName
      Tags:
        Function:
          Fn::Sub: ${AWS::StackName}-SiteSettings-${EnvStageName}
